.\"                                      Hey, EMACS: -*- nroff -*-
.TH WADC 1 "September 06, 2016"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
wadc \- Development Environment for the WadC language
.SH SYNOPSIS
.B wadc
.SH DESCRIPTION
.B wadc
is a self-contained editor for creating doom-style WAD files from a
functional programming language.
.br
A description of this language can be found in the file
.B /usr/share/doc/wadc/reference.adoc.gz
and some example programs are available within
.B /usr/share/doc/wadc/examples\ .
.PP
.SH OPTIONS
None.
.SH AUTHORS
Wouter van Oortmerssen and Jonathan Dowland.
.PP
This manual page was written by Jonathan Dowland <jmtd@debian.org>,
based on a template created by the
.B dh_make
program, for the Debian Project. It may be used by others
(see
.B /usr/share/doc/wadc/copyright.gz
).
