/*
 * hexenthings.h - part of WadC
 * Copyright © 2016 Jonathan Dowland <jon@dow.land>
 *
 * Distributed under the terms of the GNU GPL Version 2
 * See file LICENSE.txt
 *
 * hexenthings.h - thing IDs for Hexen (needs work)
 */

             mapspot            { setthing(9001) }
      mapspotgravity            { setthing(9013) }
               flame            { setthing(10500) }
               flame2           { setthing(10502) }
               flame3           { setthing(10501) }
               flame4           { setthing(10503) }
       healingbottle            { setthing(81) }
         healthflask            { setthing(82) }
             artifly            { setthing(83) }
 artiinvulnerability            { setthing(84) }
      summonmaulator            { setthing(86) }
         thrustfloor            { setthing(10091) }
         thrustfloor2           { setthing(10090) }
       teleportother            { setthing(10040) }
          fogspawner            { setthing(10000) }
           fogpatchs            { setthing(10001) }
           fogpatchm            { setthing(10002) }
           fogpatchl            { setthing(10003) }
             artiegg            { setthing(30) }
       artisuperheal            { setthing(32) }
zwingedstatuenoskull            { setthing(9011) }
        zgempedestal            { setthing(9012) }
       artipuzzskull            { setthing(9002) }
      artipuzzgembig            { setthing(9003) }
      artipuzzgemred            { setthing(9004) }
   artipuzzgemgreen1            { setthing(9005) }
   artipuzzgemgreen2            { setthing(9009) }
    artipuzzgemblue1            { setthing(9006) }
    artipuzzgemblue2            { setthing(9010) }
       artipuzzbook1            { setthing(9007) }
       artipuzzbook2            { setthing(9008) }
      artipuzzskull2            { setthing(9014) }
     artipuzzfweapon            { setthing(9015) }
     artipuzzcweapon            { setthing(9016) }
     artipuzzmweapon            { setthing(9017) }
        artipuzzgear            { setthing(9018) }
       artipuzzgear2            { setthing(9019) }
       artipuzzgear3            { setthing(9020) }
       artipuzzgear4            { setthing(9021) }
           artitorch            { setthing(33) }
        artiteleport            { setthing(36) }
       artipoisonbag            { setthing(8000) }
          speedboots            { setthing(8002) }
           boostmana            { setthing(8003) }
          boostarmor            { setthing(8041) }
         blastradius            { setthing(10110) }
          healradius            { setthing(10120) }
    treedestructible            { setthing(8062) }
            pottery1            { setthing(104) }
            pottery2            { setthing(105) }
            pottery3            { setthing(106) }
            zlynched            { setthing(109) }
           bloodpool            { setthing(111) }
        ztwinedtorch            { setthing(116) }
        ztwinedtorch2           { setthing(117) }
              bridge            { setthing(118) }
          zwalltorch            { setthing(54) }
          zwalltorch2           { setthing(55) }
             zbarrel            { setthing(8100) }
             zshrub1            { setthing(8101) }
             zshrub2            { setthing(8102) }
             zbucket            { setthing(8103) }
       zpoisonshroom            { setthing(8104) }
           zfirebull            { setthing(8042) }
           zfirebull2           { setthing(8043) }
           firething            { setthing(8060) }
          brasstorch            { setthing(8061) }
        zsuitofarmor            { setthing(8064) }
               zbell            { setthing(8065) }
               zblue            { setthing(8066) }
               ziron            { setthing(8067) }
               zxmas            { setthing(8068) }
           zcauldron            { setthing(8069) }
           zcauldron2           { setthing(8070) }
         zchainbit32            { setthing(8071) }
         zchainbit64            { setthing(8072) }
           zchainend            { setthing(8073) }
           zchainend2           { setthing(8074) }
           zchainend3           { setthing(8075) }
           zchainend4           { setthing(8076) }
           zchainend5           { setthing(8077) }
               table            { setthing(8500) }
               table2           { setthing(8501) }
               table3           { setthing(8502) }
               table4           { setthing(8503) }
               table5           { setthing(8504) }
               table6           { setthing(8505) }
               table7           { setthing(8506) }
               table8           { setthing(8507) }
               table9           { setthing(8508) }
               table10          { setthing(8509) }
         teleportman            { setthing(14) }
                  fw            { setthing(8010) }
                  fw2           { setthing(123) }
                  cw            { setthing(10) }
                  cw2           { setthing(8009) }
                  mw            { setthing(8040) }
                  fw3           { setthing(12) }
                  fw4           { setthing(13) }
                  fw5           { setthing(16) }
                  cw3           { setthing(18) }
                  cw4           { setthing(19) }
                  cw5           { setthing(20) }
                  mw2           { setthing(21) }
                  mw3           { setthing(22) }
                  mw4           { setthing(23) }
                  mw5           { setthing(53) }
             centaur            { setthing(107) }
       centaurleader            { setthing(115) }
               demon            { setthing(31) }
              demon2            { setthing(8080) }
             wraithb            { setthing(10011) }
              wraith            { setthing(34) }
            minotaur            { setthing(9) }
             serpent            { setthing(121) }
       serpentleader            { setthing(120) }
              bishop            { setthing(114) }
              dragon            { setthing(254) }
               armor            { setthing(8005) }
               armor2           { setthing(8006) }
               armor3           { setthing(8007) }
               armor4           { setthing(8008) }
               mana1            { setthing(122) }
               mana2            { setthing(124) }
               mana3            { setthing(8004) }
                key1            { setthing(8030) }
                key2            { setthing(8031) }
                key3            { setthing(8032) }
                key4            { setthing(8033) }
                key5            { setthing(8034) }
                key6            { setthing(8035) }
                key7            { setthing(8036) }
                key8            { setthing(8037) }
                key9            { setthing(8038) }
                keya            { setthing(8039) }
                keyb            { setthing(8200) }
           soundwind            { setthing(1410) }
      soundwaterfall            { setthing(41) }
               ettin            { setthing(10030) }
           firedemon            { setthing(10060) }
              iceguy            { setthing(8020) }
             fighter            { setthing(10100) }
              cleric            { setthing(10101) }
                mage            { setthing(10102) }
            sorcboss            { setthing(10080) }
               korax            { setthing(10200) }
                 bat            { setthing(10225) }
