/*
 * strife/things.h - part of WadC
 * Copyright © 2016 Jonathan Dowland <jon@dow.land>
 *
 * Distributed under the terms of the GNU GPL Version 2
 * See file LICENSE.txt
 *
 * strife/things.h - thing definitions for Strife
 *
 * NOTE: this is very rough. It's derived from chocolate-strife's info.c with
 * a first-pass at de-duplicating some things by adding '2' or 'b' to the names
 * etc. - no attempt at classifying or testing them has taken place, yet. If
 * you care about Strife support, patches welcome!
 */

          fieldguard            { setthing(25) }
          shopkeeper            { setthing(116) }
          shopkeeper2           { setthing(72) }
          shopkeeper3           { setthing(73) }
          shopkeeper4           { setthing(74) }
            peasant2            { setthing(3004) }
            peasant2b           { setthing(130) }
            peasant2c           { setthing(131) }
            peasant5            { setthing(65) }
            peasant5b           { setthing(132) }
            peasant5c           { setthing(133) }
            peasant4            { setthing(66) }
            peasant4b           { setthing(134) }
            peasant4c           { setthing(135) }
            peasant6            { setthing(67) }
            peasant6b           { setthing(136) }
            peasant6c           { setthing(137) }
            peasant3            { setthing(172) }
            peasant3b           { setthing(173) }
            peasant3c           { setthing(174) }
            peasant8            { setthing(175) }
            peasant8b           { setthing(176) }
            peasant8c           { setthing(177) }
            peasant7            { setthing(178) }
            peasant7b           { setthing(179) }
            peasant7c           { setthing(180) }
            peasant1            { setthing(181) }
              zombie            { setthing(169) }
            becoming            { setthing(201) }
       zombiespawner            { setthing(170) }
                huge            { setthing(209) }
                huge2           { setthing(210) }
                huge3           { setthing(211) }
                tank            { setthing(213) }
                tank2           { setthing(214) }
                tank3           { setthing(229) }
            kneeling            { setthing(204) }
             beggar1            { setthing(141) }
             beggar2            { setthing(155) }
             beggar3            { setthing(156) }
             beggar4            { setthing(157) }
             beggar5            { setthing(158) }
              rebel1            { setthing(9) }
              rebel2            { setthing(144) }
              rebel3            { setthing(145) }
              rebel4            { setthing(149) }
              rebel5            { setthing(150) }
              rebel6            { setthing(151) }
             rleader            { setthing(64) }
            rleader2            { setthing(200) }
              reaver            { setthing(3001) }
              guard1            { setthing(3002) }
              guard2            { setthing(142) }
              guard3            { setthing(143) }
              guard4            { setthing(146) }
              guard5            { setthing(147) }
              guard6            { setthing(148) }
              guard7            { setthing(232) }
              guard8            { setthing(231) }
         shadowguard            { setthing(58) }
              pguard            { setthing(3003) }
            crusader            { setthing(3005) }
              bishop            { setthing(187) }
              oracle            { setthing(199) }
              priest            { setthing(12) }
             spectre            { setthing(129) }
             spectre2           { setthing(75) }
             spectre3           { setthing(76) }
             spectre4           { setthing(167) }
             spectre5           { setthing(168) }
              entity            { setthing(128) }
                nest            { setthing(26) }
                 pod            { setthing(198) }
            sentinel            { setthing(3006) }
             stalker            { setthing(186) }
          inquisitor            { setthing(16) }
          programmer            { setthing(71) }
         teleportman            { setthing(14) }
              turret            { setthing(27) }
                gate            { setthing(45) }
            computer            { setthing(182) }
                 inv            { setthing(2011) }
                 inv2           { setthing(2012) }
                 inv3           { setthing(83) }
           degninore            { setthing(59) }
                 inv4           { setthing(2019) }
                 inv5           { setthing(2018) }
                 key            { setthing(230) }
                 key2           { setthing(185) }
                 key3           { setthing(184) }
                 key4           { setthing(91) }
                 key5           { setthing(40) }
                 key6           { setthing(13) }
                 key7           { setthing(38) }
                 key8           { setthing(61) }
                 key9           { setthing(86) }
                 key10          { setthing(166) }
                 key11          { setthing(39) }
                 key12          { setthing(192) }
                 key13          { setthing(193) }
                 key14          { setthing(195) }
                 key15          { setthing(236) }
                 key16          { setthing(233) }
                 key17          { setthing(234) }
                 key18          { setthing(235) }
                 inv6           { setthing(2024) }
                 inv7           { setthing(2025) }
               quest            { setthing(90) }
               quest2           { setthing(52) }
                 inv8           { setthing(2026) }
                 inv9           { setthing(2027) }
              beacon            { setthing(10) }
                 inv10          { setthing(207) }
                mony            { setthing(93) }
                mony2           { setthing(138) }
                mony3           { setthing(139) }
                mony4           { setthing(140) }
                 inv11          { setthing(205) }
                 inv12          { setthing(206) }
               agren            { setthing(152) }
              apgren            { setthing(153) }
               aclip            { setthing(2007) }
            aammobox            { setthing(2048) }
               amini            { setthing(2010) }
            aminibox            { setthing(2046) }
               acell            { setthing(2047) }
              apcell            { setthing(17) }
              aparow            { setthing(115) }
               aarow            { setthing(114) }
                 inv13          { setthing(183) }
               pulse            { setthing(2002) }
          riflestand            { setthing(2006) }
        flamethrower            { setthing(2005) }
     missilelauncher            { setthing(2003) }
             blaster            { setthing(2004) }
            crossbow            { setthing(2001) }
     grenadelauncher            { setthing(154) }
               sigil            { setthing(77) }
               sigil2           { setthing(78) }
               sigil3           { setthing(79) }
               sigil4           { setthing(80) }
               sigil5           { setthing(81) }
               power            { setthing(92) }
                 rat            { setthing(85) }
             light14            { setthing(95) }
             light13            { setthing(96) }
             light12            { setthing(97) }
             light18            { setthing(2028) }
             pillar2            { setthing(48) }
             pillar3            { setthing(54) }
             pillar4            { setthing(55) }
             pillar5            { setthing(56) }
             pillar6            { setthing(57) }
             pillar7            { setthing(227) }
               cave2            { setthing(98) }
               cave3            { setthing(161) }
               cave4            { setthing(160) }
               cave6            { setthing(159) }
               cave7            { setthing(162) }
               cave5            { setthing(163) }
              light2            { setthing(34) }
              light3            { setthing(35) }
                bio2            { setthing(113) }
       teleportstand            { setthing(23) }
          deadthing1            { setthing(22) }
          deadthing2            { setthing(15) }
          deadthing3            { setthing(18) }
          deadthing4            { setthing(21) }
          deadthing5            { setthing(20) }
          deadthing6            { setthing(19) }
                bio1            { setthing(212) }
                gibs            { setthing(54) }
             light11            { setthing(105) }
             light10            { setthing(106) }
              light9            { setthing(107) }
              light8            { setthing(108) }
              light1            { setthing(28) }
             pillar8            { setthing(110) }
             pillar9            { setthing(44) }
             light15            { setthing(111) }
              light4            { setthing(43) }
              light5            { setthing(46) }
               rock1            { setthing(99) }
               rock2            { setthing(100) }
               rock3            { setthing(101) }
               rock4            { setthing(102) }
               tree7            { setthing(215) }
             rubble1            { setthing(29) }
             rubble2            { setthing(30) }
             rubble3            { setthing(31) }
             rubble4            { setthing(32) }
             rubble5            { setthing(36) }
             rubble6            { setthing(37) }
             rubble7            { setthing(41) }
             rubble8            { setthing(42) }
              light6            { setthing(47) }
              light7            { setthing(50) }
               tree2            { setthing(51) }
               tree3            { setthing(202) }
               tree4            { setthing(203) }
               tree1            { setthing(33) }
               tree6            { setthing(60) }
               tree5            { setthing(62) }
               cave1            { setthing(63) }
             pillar1            { setthing(69) }
             light16            { setthing(196) }
             light17            { setthing(197) }
            coupling            { setthing(220) }
            coupling2           { setthing(226) }
            pillar10            { setthing(221) }
            pillar11            { setthing(222) }
            pillar12            { setthing(223) }
            pillar13            { setthing(224) }
             light19            { setthing(225) }
