.TH WADC 6 "September 24, 2015"
.SH NAME
wadcc \- command-line interface for Wad Compiler
.SH SYNOPSIS
.B wadcc
.I infile
.SH DESCRIPTION
.B wadcc
is a command-line interface for Wad Compiler, a tool
for creating doom-style WAD files from a functional
programming language.
.br
A description of this language can be found in the file
.B /usr/share/doc/wadc/reference.adoc.gz
and some example programs are available within
.B /usr/share/doc/wadc/examples\ .
.PP
.SH OPTIONS
None.
.SH AUTHORS
Jonathan Dowland.
.PP
This manual page was written by Jonathan Dowland <jmtd@debian.org>,
based on a template created by the
.B dh_make
program, for the Debian Project. It may be used by others
(see
.B /usr/share/doc/wadc/copyright.gz
).
